Parity validation
curiouslearning/followthelearners pull request #458
Opened 2020-12-11 05:02 UTC by ddave2122

Added a stand-alone file that can run parity checks for donations in our Firebase system and Stripe.  Once we know how we want to display the data, we can modify the output

2020-12-11 14:54 UTC, bookjunkie93 requested changes
does this need to be a hotfix or can we merge into the `develop` branch first?

2020-12-11 14:54 UTC, bookjunkie93 commented on donation-parity-validation.js
> +const {apiKey} = require('../keys/stripe.json')
the keys directory is in the project root and so is this script

2020-12-11 14:54 UTC, bookjunkie93 commented on donation-parity-validation.js
> +const serviceAccount = require('../keys/firestore-key.json');
path to key should be ./keys/firestore-key.json

2020-12-22 08:19 UTC, ddave2122 commented
Base branch changed to `develop`.  Good catch!

2020-12-23 15:18 UTC, bookjunkie93 approved these changes

2020-12-23 15:18 UTC, merged