Gd fixed map controls
curiouslearning/followthelearners pull request #525
Opened 2021-02-17 15:54 UTC by redpixr

- Adjust navbar scrolling
- Fix map controls and & automatic scrolling

2021-02-17 18:42 UTC, bookjunkie93 requested changes

2021-02-17 18:42 UTC, bookjunkie93 commented on static/js/navbar.ts
> +      if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
extract these into a config value

2021-02-17 19:20 UTC, redpixr commented on static/js/navbar.ts
> +      if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
On it!

2021-02-19 16:03 UTC, redpixr commented
@bookjunkie93 Ready for a review!

2021-02-19 16:21 UTC, bookjunkie93 approved these changes

2021-02-19 17:52 UTC, merged